### ISSUE TITLE
Error: unexpected end of file

### ISSUE THREAD

**Issue by Minisector** [valiquette/homebridge-my-wallbox#15]
Hello there, I keep on getting the following error: "[Wallbox] Error getting token unexpected end of file"

When enabling debug on HomeBridge, here's what I get:

```

[08/12/2022, 19:46:25] [Wallbox] check email response {
  "data": {
    "type": "user_email",
    "id": "myemail@pm.me",
    "attributes": {
      "status": "confirmed"
    }
  }
}
[08/12/2022, 19:46:25] [Wallbox] Email status confirmed
[08/12/2022, 19:46:25] [Wallbox] Retrieving token
[08/12/2022, 19:46:25] [Wallbox] {
  "message": "unexpected end of file",
  "name": "Error",
  "stack": "Error: unexpected end of file\n    at Function.AxiosError.from (/usr/lib/node_modules/homebridge-my-wallbox/node_modules/axios/lib/core/AxiosError.js:89:14)\n    at BrotliDecompress.handleStreamError (/usr/lib/node_modules/homebridge-my-wallbox/node_modules/axios/lib/adapters/http.js:489:29)\n    at BrotliDecompress.emit (node:events:525:35)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "adapter": [
      "xhr",
      "http"
    ],
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {
      "Blob": null
    },
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json",
      "Authorization": "Basic ZmxlY2NhQHBtLm1lOkBnbEBLQHIxY0A=",
      "Partner": "wallbox",
      "User-Agent": "homebridge-my-wallbox/1.1.4",
      "Accept-Encoding": "gzip, compress, deflate, br"
    },
    "method": "get",
    "baseURL": "https://user-api.wall-box.com/users",
    "url": "/signin",
    "responseType": "json"
  },
  "code": "Z_BUF_ERROR",
  "status": null
}
[08/12/2022, 19:46:25] [Wallbox] Error getting token unexpected end of file
[08/12/2022, 19:46:25] [Wallbox] Failed to get devices...TypeError: Cannot read properties of undefined (reading 'data')
    at wallboxPlatform.getDevices (/usr/lib/node_modules/homebridge-my-wallbox/wallboxplatform.js:77:45)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
Retrying in 60 seconds...
```

What am I doing wrong? Please advise... thanks!!!
MS

**Comment by valiquette** [comment]
No, you're good.  Something changed on the API response and I now need to be more specific to what is accepted. 
new update 1.1.5 fixes this.

**Comment by Minisector** [comment]
It works now. Thank you!
